name: Publish Docker image on edge tag
on:
  push:

jobs:
    push_to_registry:
        name: Publish Docker image on edge tag
        environment:
            name: Push Docker image to Docker hub
            url: https://api.air-balloon.cloud
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            max-parallel: 4
            matrix:
                include:
                    #- { platform: "linux/arm64", platform-tag: "arm64" }
                    - { platform: "linux/amd64", platform-tag: "amd64" }
                    #- { platform: "linux/arm/v7", platform-tag: "armv7" }
                    #- { platform: "linux/arm/v6", platform-tag: "armv6" }
                    #- { platform: "linux/ppc64le", platform-tag: "ppc64le" }
                    #- { platform: "linux/riscv64", platform-tag: "riscv64" }
                    #- { platform: "linux/s390x", platform-tag: "s390x" }
                    #- { platform: "linux/386", platform-tag: "386" }
                    #- { platform: "linux/mips64le", platform-tag: "mips64le" }
                    #- { platform: "linux/mips64", platform-tag: "mips64" }
        steps:
            - uses: actions/checkout@v2
            # https://github.com/docker/setup-qemu-action
            - name: Set up QEMU
              uses: docker/setup-qemu-action@v1
            # https://github.com/docker/setup-buildx-action
            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v1

            - name: Cache Docker layers
              uses: actions/cache@v2
              with:
                path: /tmp/.buildx-cache
                # Key is named differently to avoid collision
                key: ${{ runner.os }}-${{ matrix.platform-tag }}-multi-buildx-${{ github.sha }}
                restore-keys: |
                    ${{ runner.os }}-${{ matrix.platform-tag }}-multi-buildx

            - name: Build image
              run: make docker-build
              env:
                PLATFORM: "${{ matrix.platform }}"
                IMAGE_TAG: "docker.io/airballoon/api:edge"
                # Note the mode=max here
                # More: https://github.com/moby/buildkit#--export-cache-options
                # And: https://github.com/docker/buildx#--cache-tonametypetypekeyvalue
                BUILDX_CLI_ARGS: "--cache-from=type=local,src=/tmp/.buildx-cache --cache-to=type=local,mode=max,dest=/tmp/.buildx-cache-new"

            - name: Move cache
              run: |
                rm -rf /tmp/.buildx-cache
                mv /tmp/.buildx-cache-new /tmp/.buildx-cache

            - name: Login to DockerHub
              uses: docker/login-action@v1
              with:
                registry: docker.io
                username: ${{ secrets.DOCKER_REPOSITORY_LOGIN }}
                password: ${{ secrets.DOCKER_REPOSITORY_PASSWORD }}
            - name: Sign and push docker image
              uses: sudo-bot/action-docker-sign@latest
              with:
                image-ref: "docker.io/airballoon/api:edge"
                private-key-id: "${{ secrets.DOCKER_PRIVATE_KEY_ID }}"
                private-key: ${{ secrets.DOCKER_PRIVATE_KEY }}
                private-key-passphrase: ${{ secrets.DOCKER_PRIVATE_KEY_PASSPHRASE }}
