name: Build and test rust code

on: [push]

jobs:
    build:
        runs-on: ubuntu-latest
        environment:
            name: Build Docker images
        strategy:
            fail-fast: false
            max-parallel: 4
            matrix:
                include:
                    #- { platform: "linux/arm64", platform-tag: "arm64" }
                    - { platform: "linux/amd64", platform-tag: "amd64" }
                    #- { platform: "linux/arm/v7", platform-tag: "armv7" }
                    #- { platform: "linux/arm/v6", platform-tag: "armv6" }
                    #- { platform: "linux/ppc64le", platform-tag: "ppc64le" }
                    #- { platform: "linux/riscv64", platform-tag: "riscv64" }
                    #- { platform: "linux/s390x", platform-tag: "s390x" }
                    #- { platform: "linux/386", platform-tag: "386" }
                    #- { platform: "linux/mips64le", platform-tag: "mips64le" }
                    #- { platform: "linux/mips64", platform-tag: "mips64" }
        steps:
            - uses: actions/checkout@v2
            # https://github.com/docker/setup-qemu-action
            - name: Set up QEMU
              uses: docker/setup-qemu-action@v1
            # https://github.com/docker/setup-buildx-action
            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v1

            - name: Cache Docker layers
              uses: actions/cache@v2
              with:
                path: /tmp/.buildx-cache
                # Key is named differently to avoid collision
                key: ${{ runner.os }}-${{ matrix.platform-tag }}-multi-buildx-${{ github.sha }}
                restore-keys: |
                    ${{ runner.os }}-${{ matrix.platform-tag }}-multi-buildx

            - name: Build image
              run: make docker-build
              env:
                PLATFORM: "${{ matrix.platform }}"
                IMAGE_TAG: "docker.io/airballoon/api:${{ matrix.platform-tag }}-edge"
                # Note the mode=max here
                # More: https://github.com/moby/buildkit#--export-cache-options
                # And: https://github.com/docker/buildx#--cache-tonametypetypekeyvalue
                BUILDX_CLI_ARGS: "--cache-from=type=local,src=/tmp/.buildx-cache --cache-to=type=local,mode=max,dest=/tmp/.buildx-cache-new"

            - name: Move cache
              run: |
                rm -rf /tmp/.buildx-cache
                mv /tmp/.buildx-cache-new /tmp/.buildx-cache

    test:
        needs: build
        runs-on: ubuntu-latest
        steps:
            - name: Cache cargo registry
              uses: actions/cache@v2
              with:
                  path: ~/.cargo/registry
                  key: ${{ runner.os }}-cargo-registry-${{ hashFiles('**/Cargo.lock') }}
            - name: Cache cargo index
              uses: actions/cache@v2
              with:
                  path: ~/.cargo/git
                  key: ${{ runner.os }}-cargo-index-${{ hashFiles('**/Cargo.lock') }}
            - name: Cache cargo build
              uses: actions/cache@v2
              with:
                  path: target
                  key: ${{ runner.os }}-cargo-test-build-target-${{ hashFiles('**/Cargo.lock') }}
            - name: Checkout repository
              uses: actions/checkout@v2
            - name: Set up toolchain
              uses: actions-rs/toolchain@v1
              with:
                  profile: minimal
                  toolchain: stable
                  override: true
            - name: Test
              uses: actions-rs/cargo@v1
              with:
                  command: test
